// File generated by Antigravity (Dummy placeholder)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxN6pNWxp_W4oSGaCAT12lArZW3UkvMHM',
    appId: '1:155765340966:web:0084f96381356c14c01fe7',
    messagingSenderId: '155765340966',
    projectId: 'real-estate-owner',
    authDomain: 'real-estate-owner.firebaseapp.com',
    storageBucket: 'real-estate-owner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsW_juIn4gcEN3s8OyQSKm4DzqMq-5RqY',
    appId: '1:155765340966:android:cfd177ceb8d66a06c01fe7',
    messagingSenderId: '155765340966',
    projectId: 'real-estate-owner',
    storageBucket: 'real-estate-owner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSB8AyU3vyhV7XCCxEEIc1kXWw-nuVlgc',
    appId: '1:155765340966:ios:c372cbb2ae3f323dc01fe7',
    messagingSenderId: '155765340966',
    projectId: 'real-estate-owner',
    storageBucket: 'real-estate-owner.firebasestorage.app',
    iosBundleId: 'com.example.realEstateOwnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSB8AyU3vyhV7XCCxEEIc1kXWw-nuVlgc',
    appId: '1:155765340966:ios:c372cbb2ae3f323dc01fe7',
    messagingSenderId: '155765340966',
    projectId: 'real-estate-owner',
    storageBucket: 'real-estate-owner.firebasestorage.app',
    iosBundleId: 'com.example.realEstateOwnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxN6pNWxp_W4oSGaCAT12lArZW3UkvMHM',
    appId: '1:155765340966:web:0085f961f0d03d7ec01fe7',
    messagingSenderId: '155765340966',
    projectId: 'real-estate-owner',
    authDomain: 'real-estate-owner.firebaseapp.com',
    storageBucket: 'real-estate-owner.firebasestorage.app',
  );

}